title: Learn
description: My learning documentation site
remote_theme: just-the-docs/just-the-docs

url: https://yadnyeshkolte.github.io
baseurl: /learn

# Enable search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/yadnyeshkolte/learn"
